import * as THREE from 'three';
import { GLTFLoader } from 'three/addons/loaders/GLTFLoader.js';

const host=document.querySelector('#game');
const scene=new THREE.Scene();scene.background=new THREE.Color(0x91d7e8);scene.fog=new THREE.Fog(0x91d7e8,35,120);
const camera=new THREE.PerspectiveCamera(53,innerWidth/innerHeight,.1,180);camera.position.set(0,5.2,10.5);camera.lookAt(0,1,3.2);
const renderer=new THREE.WebGLRenderer({antialias:true,alpha:false});renderer.setPixelRatio(Math.min(devicePixelRatio,2));renderer.setSize(innerWidth,innerHeight);renderer.shadowMap.enabled=true;renderer.shadowMap.type=THREE.PCFSoftShadowMap;renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=1.12;host.appendChild(renderer.domElement);
scene.add(new THREE.HemisphereLight(0xe5fbff,0x8a7651,2.2));const sun=new THREE.DirectionalLight(0xfff1c9,3.2);sun.position.set(-7,13,7);sun.castShadow=true;sun.shadow.mapSize.set(1024,1024);scene.add(sun);
const mat=(color,roughness=.85)=>new THREE.MeshStandardMaterial({color,roughness});
const mats={sand:mat(0xd9bd7d),track:mat(0x8e8270),rail:mat(0x748b8c,.5),wood:mat(0xa8754f),gold:mat(0xffcf43,.45),cream:mat(0xfff4d7),teal:mat(0x49b9b0),coral:mat(0xf38260),green:mat(0x82bd79),building:mat(0xf0d7a1),window:mat(0x73bdc5,.38),shadow:mat(0x716454)};
const box=(w,h,d,material,x=0,y=0,z=0,parent=scene)=>{const o=new THREE.Mesh(new THREE.BoxGeometry(w,h,d),material);o.position.set(x,y,z);o.castShadow=true;o.receiveShadow=true;parent.add(o);return o};
const sphere=(r,material,x,y,z,parent=scene)=>{const o=new THREE.Mesh(new THREE.SphereGeometry(r,20,14),material);o.position.set(x,y,z);o.castShadow=true;parent.add(o);return o};

// Ground, three lanes, rails, sleepers, and simple sunny-town scenery.
const MAP_LENGTH=620,MAP_CENTER=-300;
const floor=box(40,.15,MAP_LENGTH,mats.sand,0,-.15,MAP_CENTER);floor.receiveShadow=true;
const track=box(8,.08,MAP_LENGTH,mats.track,0,-.055,MAP_CENTER);
for(let x of [-3.05,-1.02,1.02,3.05]){box(.09,.09,MAP_LENGTH,mats.rail,x,.02,MAP_CENTER)}
const sleepers=[];for(let i=0;i<160;i++){sleepers.push(box(7.8,.07,.22,mats.wood,0,.015,7-i*3.8))}
for(let side of [-1,1]){box(18,.1,MAP_LENGTH,mats.sand,side*13,-.03,MAP_CENTER);for(let j=0;j<55;j++){let z=-6-j*10;let w=3+Math.random()*2,h=3+Math.random()*5;const b=box(w,h,4,j%3===0?mats.teal:mats.building,side*(7+Math.random()*2),h/2-.05,z);box(w*.55,h*.22,.08,mats.window,b.position.x,h*.64,z-2.03);box(w*.55,h*.22,.08,mats.window,b.position.x,h*.38,z-2.03);box(.14,h*.8,.1,mats.coral,b.position.x-w*.25,h*.5,z-2.05)}
  for(let j=0;j<76;j++){let z=-5-j*7.5;let trunk=box(.22,1.2,.22,mats.wood,side*5.2,.6,z);const crown=sphere(.78,mats.green,side*5.2,1.6,z);crown.scale.set(1,1.25,1)}
}
// Distant pastel sky puffs.
for(let i=0;i<18;i++){let cloud=new THREE.Group();let x=(Math.random()-.5)*70,y=14+Math.random()*12,z=-35-Math.random()*70;for(let k=0;k<4;k++)sphere(1.3+Math.random()*.8,new THREE.MeshStandardMaterial({color:0xffffff,roughness:1}),x+(k-1.5)*1.5,y+Math.random(),z,cloud);scene.add(cloud)}

const lanes=[-2,0,2];let currentLane=1,targetX=0;const runner=new THREE.Group();scene.add(runner);runner.position.set(0,0,3.2);const avatar=new THREE.Group();runner.add(avatar);let modelLoaded=false;const accessoryGroup=new THREE.Group();avatar.add(accessoryGroup);
let selectedMap='sunny',selectedOutfit='scarf';
const mapThemes={sunny:{name:'阳光铁路',sky:0x91d7e8,sand:0xd9bd7d,track:0x8e8270,rail:0x748b8c,wood:0xa8754f,building:0xf0d7a1,window:0x73bdc5,green:0x82bd79,teal:0x49b9b0,coral:0xf38260},coast:{name:'海风栈道',sky:0x88d9e7,sand:0xd8d3ad,track:0x839e9b,rail:0xd4e0d8,wood:0x987750,building:0xf4e4bb,window:0x48b8ce,green:0x63b89b,teal:0x5ab8bc,coral:0xf5a46c},candy:{name:'糖果小镇',sky:0xc6c8ef,sand:0xe7c7db,track:0x8e819c,rail:0xf0d6ed,wood:0xc28d92,building:0xf7d6cb,window:0x80cbd0,green:0x8fc8a1,teal:0x7abfc2,coral:0xe991ae}};
function selectMap(key){const t=mapThemes[key]||mapThemes.sunny;selectedMap=key;scene.background.setHex(t.sky);scene.fog.color.setHex(t.sky);for(const n of ['sand','track','rail','wood','building','window','green','teal','coral'])mats[n].color.setHex(t[n]);document.querySelector('#home-map-name').textContent=t.name;document.querySelector('#play-map-name').textContent=t.name;document.querySelectorAll('[data-map]').forEach(b=>{const on=b.dataset.map===key;b.classList.toggle('selected',on);b.querySelector('i').textContent=on?'✓':''})}
function selectOutfit(key){selectedOutfit=key;while(accessoryGroup.children.length)accessoryGroup.remove(accessoryGroup.children[0]);const scarfMat=mat(key==='cap'?0xffbd4c:key==='pack'?0x45aeb1:0x56c5a1,.68),darkMat=mat(key==='pack'?0x397c81:0x318773,.72);if(key==='scarf'){const loop=new THREE.Mesh(new THREE.TorusGeometry(.32,.085,10,28),scarfMat);loop.rotation.x=Math.PI/2;loop.position.set(0,1.48,.02);loop.scale.set(1,.72,1);accessoryGroup.add(loop);const tail=box(.16,.35,.12,darkMat,.19,1.26,.19,accessoryGroup);tail.rotation.z=-.2}else if(key==='cap'){const dome=new THREE.Mesh(new THREE.SphereGeometry(.35,24,14,0,Math.PI*2,0,Math.PI/2),scarfMat);dome.position.set(0,1.91,0);accessoryGroup.add(dome);const brim=box(.56,.08,.34,darkMat,0,1.89,.19,accessoryGroup);brim.rotation.x=-.08}else{const bag=box(.48,.54,.24,scarfMat,0,1.16,-.43,accessoryGroup);bag.rotation.x=-.08;box(.26,.13,.08,darkMat,0,1.2,-.57,accessoryGroup);for(const s of [-1,1]){const strap=box(.09,.5,.1,darkMat,s*.28,1.2,-.24,accessoryGroup);strap.rotation.z=s*.1}}document.querySelectorAll('[data-outfit]').forEach(b=>{const on=b.dataset.outfit===key;b.classList.toggle('selected',on);b.querySelector('i').textContent=on?'✓':''})}
function fallbackNaiwa(){const yellow=mat(0xffcd42),white=mat(0xfff3dc),green=mat(0x54b87f),black=mat(0x101c1a),brown=mat(0x51402c);let body=sphere(.72,yellow,0,1.2,0,avatar);body.scale.set(.95,1.1,.75);let head=sphere(.43,yellow,0,2.12,0,avatar);head.scale.set(.87,1.03,.72);sphere(.52,white,0,1.15,-.67,avatar).scale.set(1,.7,.2);for(let s of [-1,1]){sphere(.115,green,s*.21,2.28,.53,avatar);sphere(.065,black,s*.21,2.28,.62,avatar);let arm=sphere(.2,yellow,s*.82,1.15,0,avatar);arm.scale.set(.7,1.6,.8);let hand=sphere(.14,brown,s*.9,.52,.04,avatar);hand.scale.set(.8,1.15,.8);let leg=sphere(.18,yellow,s*.36,.32,0,avatar);leg.scale.set(.7,1.3,.8);let foot=sphere(.19,brown,s*.38,.12,.16,avatar);foot.scale.set(1.1,.55,1.5)}}
new GLTFLoader().load('./assets/nailong-runner.glb',g=>{const m=g.scene;let b=new THREE.Box3().setFromObject(m);let h=b.getSize(new THREE.Vector3()).y;let s=2.05/h;m.scale.setScalar(s);b=new THREE.Box3().setFromObject(m);m.position.y=-b.min.y;avatar.add(m);modelLoaded=true;},undefined,err=>{console.warn('奶娃模型加载失败，使用备用造型',err);fallbackNaiwa()});
selectOutfit(selectedOutfit);selectMap(selectedMap);

// Shadow puddle under the runner.
const shadow=new THREE.Mesh(new THREE.CircleGeometry(.82,32),new THREE.MeshBasicMaterial({color:0x665b45,transparent:true,opacity:.2,depthWrite:false}));shadow.rotation.x=-Math.PI/2;shadow.position.set(0,.012,3.2);scene.add(shadow);
const entities=[];const coinGeo=new THREE.TorusGeometry(.22,.075,10,22);
function addCoin(lane,z,y=1.1){const group=new THREE.Group();group.position.set(lanes[lane],y,z);const ring=new THREE.Mesh(coinGeo,mats.gold);ring.rotation.x=Math.PI/2;ring.castShadow=true;group.add(ring);sphere(.055,mats.cream,0,0,.01,group);scene.add(group);entities.push({group,type:'coin',lane,y,hit:false})}
function addObstacle(lane,z,type){const group=new THREE.Group();group.position.set(lanes[lane],0,z);if(type==='jump'){box(1.25,.42,.48,mats.coral,0,.24,0,group);box(1.36,.09,.55,mats.cream,0,.47,0,group);for(let x of [-.43,.43])sphere(.08,mats.gold,x,.54,0,group)}else if(type==='slide'){box(.13,1.5,.14,mats.teal,-.62,.75,0,group);box(.13,1.5,.14,mats.teal,.62,.75,0,group);box(1.36,.2,.3,mats.coral,0,1.48,0,group);box(1.06,.12,.3,mats.cream,0,1.33,0,group)}else{box(1.1,1.45,1.0,mats.building,0,.73,0,group);box(.82,.67,.08,mats.coral,0,.86,-.53,group);box(.45,.18,.09,mats.cream,0,1.32,-.54,group)}scene.add(group);entities.push({group,type,lane,hit:false})}
function spawnSet(z){const lane=Math.floor(Math.random()*3),patterns=[['jump'],['slide'],['block'],['jump','block'],['coinline','jump'],['coinline','slide']];const p=patterns[Math.floor(Math.random()*patterns.length)];if(p[0]==='coinline'){for(let i=0;i<6;i++)addCoin(lane,z-i*1.45,1.12+(i===2?.35:0));addObstacle(lane,z-10,p[1])}else{addObstacle(lane,z,p[0]);let safe=(lane+1+Math.floor(Math.random()*2))%3;if(Math.random()>.35)for(let i=0;i<4;i++)addCoin(safe,z-3-i*1.55,1.05)}}
for(let i=0;i<8;i++)spawnSet(-34-i*16);

let state='home',distance=0,coins=0,speed=18,elapsed=0,jumpTime=0,slideTime=0,spawnTimer=0,lastTime=performance.now(),snackCount=3,energy=80;const overlay=document.querySelector('#overlay'),overlayTitle=document.querySelector('#overlay-title'),overlayCopy=document.querySelector('#overlay-copy'),startBtn=document.querySelector('#start'),homeScreen=document.querySelector('#home-screen'),appShell=document.querySelector('#app-shell');
function setOverlay(title,copy,button='开始跑酷'){overlayTitle.textContent=title;overlayCopy.textContent=copy;startBtn.innerHTML=button+' <span>➜</span>';overlay.classList.remove('hidden')}
function begin(){entities.forEach(e=>scene.remove(e.group));entities.length=0;for(let i=0;i<8;i++)spawnSet(-34-i*16);currentLane=1;targetX=0;runner.position.set(0,0,3.2);runner.rotation.y=0;avatar.rotation.y=Math.PI;distance=0;coins=0;speed=18;elapsed=0;jumpTime=0;slideTime=0;spawnTimer=0;state='running';homeScreen.classList.add('hidden');appShell.classList.remove('home-mode');overlay.classList.add('hidden');document.querySelector('#status').textContent='注意前方障碍，沿途收集奶星！';document.querySelector('#hint').textContent='收集奶星，挑战更远距离！'}
function endGame(){state='over';document.querySelector('#status').textContent='本次跑酷结束';setOverlay('跑酷结束！',`跑了 ${Math.floor(distance)} 米，收集 ${coins} 颗奶星。再跑一局刷新纪录吧。`,'再跑一次')}
function act(action){if(state!=='running')return;if(action==='left'||action==='right'){currentLane=THREE.MathUtils.clamp(currentLane+(action==='left'?-1:1),0,2);targetX=lanes[currentLane]}else if(action==='jump'&&jumpTime<=0&&slideTime<=0)jumpTime=.78;else if(action==='slide'&&slideTime<=0&&jumpTime<=0)slideTime=.78}
addEventListener('keydown',e=>{const key=e.key.toLowerCase();if(['arrowleft','arrowright','arrowup','arrowdown',' '].includes(key))e.preventDefault();if(key==='arrowleft'||key==='a')act('left');if(key==='arrowright'||key==='d')act('right');if(key==='arrowup'||key==='w'||key===' ')act('jump');if(key==='arrowdown'||key==='s')act('slide');if(key==='enter'&&state!=='running')begin();if(key==='escape')togglePause()});
document.querySelectorAll('[data-action]').forEach(btn=>{btn.addEventListener('pointerdown',e=>{e.preventDefault();act(btn.dataset.action)})});
let touchStart=null;renderer.domElement.addEventListener('pointerdown',e=>{if(e.pointerType==='touch')touchStart={x:e.clientX,y:e.clientY}});renderer.domElement.addEventListener('pointerup',e=>{if(!touchStart)return;const dx=e.clientX-touchStart.x,dy=e.clientY-touchStart.y;if(Math.max(Math.abs(dx),Math.abs(dy))>30){if(Math.abs(dx)>Math.abs(dy))act(dx<0?'left':'right');else act(dy<0?'jump':'slide')}touchStart=null});
function togglePause(){if(state==='running'){state='paused';setOverlay('休息一下',`已跑 ${Math.floor(distance)} 米，收集 ${coins} 颗奶星。`,'继续跑');startBtn.onclick=()=>{state='running';overlay.classList.add('hidden');startBtn.onclick=begin}}else if(state==='paused'){state='running';overlay.classList.add('hidden')}}
function returnHome(){state='home';homeScreen.classList.remove('hidden');appShell.classList.add('home-mode');avatar.rotation.y=0;runner.rotation.y=0;overlay.classList.add('hidden')}
startBtn.addEventListener('click',()=>{if(state==='paused'){state='running';overlay.classList.add('hidden')}else if(state==='help'){state='home';overlay.classList.add('hidden')}else begin()});document.querySelector('#pause').addEventListener('click',togglePause);document.querySelector('#play-button').addEventListener('click',begin);document.querySelector('#home-button').addEventListener('click',returnHome);
document.querySelector('#help-button').addEventListener('click',()=>{state='help';setOverlay('怎么玩？','左右换道躲开障碍，跳过矮路障，滑铲穿过横杆。跑得越远，速度越快；沿途收集奶星吧！','知道了')});
document.querySelectorAll('[data-home-tab]').forEach(b=>b.addEventListener('click',()=>{const maps=b.dataset.homeTab==='maps';document.querySelectorAll('[data-home-tab]').forEach(t=>{const on=t===b;t.classList.toggle('selected',on);t.setAttribute('aria-selected',String(on))});document.querySelector('#wardrobe-panel').classList.toggle('hidden',maps);document.querySelector('#maps-panel').classList.toggle('hidden',!maps)}));
document.querySelectorAll('[data-outfit]').forEach(b=>b.addEventListener('click',()=>selectOutfit(b.dataset.outfit)));document.querySelectorAll('[data-map]').forEach(b=>b.addEventListener('click',()=>selectMap(b.dataset.map)));
document.querySelector('#feed-button').addEventListener('click',()=>{if(state!=='home'||snackCount<1)return;snackCount--;energy=Math.min(100,energy+10);document.querySelector('#snack-count').textContent=snackCount;document.querySelector('#snack-inline').textContent=snackCount;document.querySelector('#energy-label').textContent=energy+'%';document.querySelector('#energy-bar').style.width=energy+'%';document.querySelector('#pet-mood').textContent=snackCount?'奶娃吃得很开心，活力增加啦！':'奶娃吃饱啦，准备出发吧！';const fx=document.querySelector('#feed-fx');fx.textContent='🍮  ✨  💛';fx.classList.remove('pop');void fx.offsetWidth;fx.classList.add('pop');avatar.scale.setScalar(1.08);setTimeout(()=>avatar.scale.setScalar(1),320)});

function animate(now){requestAnimationFrame(animate);const dt=Math.min((now-lastTime)/1000,.04);lastTime=now;elapsed+=dt;if(state==='running'){speed=Math.min(18+distance*.035,38);const movement=speed*dt;distance+=movement*.45;runner.position.x=THREE.MathUtils.damp(runner.position.x,targetX,10,dt);const bob=Math.sin(elapsed*13)*.045;let lift=0;if(jumpTime>0){jumpTime=Math.max(0,jumpTime-dt);lift=Math.sin((1-jumpTime/.78)*Math.PI)*1.08}if(slideTime>0)slideTime=Math.max(0,slideTime-dt);avatar.position.y=lift+bob;avatar.scale.y=slideTime>0?.57:1;avatar.rotation.z=THREE.MathUtils.damp(avatar.rotation.z,(targetX-runner.position.x)*-.09,8,dt);shadow.scale.setScalar(1-lift*.22);shadow.material.opacity=.2-lift*.1;
    sleepers.forEach(o=>{o.position.z+=movement;if(o.position.z>12)o.position.z-=MAP_LENGTH});entities.forEach(e=>{e.group.position.z+=movement;if(e.type==='coin'){e.group.rotation.y+=dt*2.4;e.group.position.y=e.y+Math.sin(elapsed*5+e.group.position.z)*.08;if(!e.hit&&Math.abs(e.group.position.z-runner.position.z)<.78&&e.lane===currentLane){e.hit=true;coins++;scene.remove(e.group)}}else if(!e.hit&&Math.abs(e.group.position.z-runner.position.z)<.68&&e.lane===currentLane){let bypass=e.type==='jump'?jumpTime>.14:e.type==='slide'?slideTime>.12:false;if(!bypass){e.hit=true;endGame()}}});for(let i=entities.length-1;i>=0;i--)if(entities[i].hit||entities[i].group.position.z>14){scene.remove(entities[i].group);entities.splice(i,1)}spawnTimer+=dt;if(spawnTimer>1.8){spawnSet(-104-Math.random()*12);spawnTimer=0}
    document.querySelector('#distance').textContent=Math.floor(distance);document.querySelector('#coins').textContent=coins;document.querySelector('#speed').textContent=Math.round(speed*1.45);document.querySelector('#speedbar').style.width=`${Math.min(100,(speed-18)*4.4)}%`;
  }else if(state==='home'||state==='help'){avatar.position.y=Math.sin(elapsed*2)*.035;avatar.rotation.y=Math.sin(elapsed*.75)*.08}
  camera.position.x=THREE.MathUtils.damp(camera.position.x,runner.position.x*.16,2,dt);camera.lookAt(runner.position.x*.13,1.05,runner.position.z);renderer.render(scene,camera)}requestAnimationFrame(animate);
addEventListener('resize',()=>{camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix();renderer.setSize(innerWidth,innerHeight);renderer.setPixelRatio(Math.min(devicePixelRatio,2))});
